version: "3"

services:

  caol-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caol-frontend
    restart: always
    networks:
      - caol-network

networks:
  caol-network:
    external: true
